  steps:
    - label: Bon 9
#      plugins:
#        - docker#v5.12.0:
#            image: "huggingface/transformers-torch-light"
#            always-pull: true
      commands:
        - "echo 9"
        - "pwd"
        - "echo $(python3 --version)"
      parallelism: 2

    - label: Mal 10
      plugins:
        - docker#v5.12.0:
            image: "huggingface/transformers-torch-light"
            always-pull: true
      commands:
        - "echo 10"
        - "pwd"
        - "echo 1"
        - "ls -la"
        - "echo 2"
        - "ls -la /"
        - "echo 3"
        - "ls -la /workdir"
        - "echo 4"
        - "ls -la /root"
        - "echo 5"
        - "ls -la /home"
#        - "python3 -m pytest -v tests/models/vit/test_modeling_vit.py::ViTModelTest::test_config"
        - "python3 -m pytest -v tests/models/vit/test_modeling_vit.py -k ViTModelTest"
      parallelism: 2
