  steps:
    - label: Bon 9
#      plugins:
#        - docker#v5.12.0:
#            image: "huggingface/transformers-torch-light"
#            always-pull: true
      commands:
        - "echo 9"
        - "pwd"
        - "echo $(python3 --version)"
      parallelism: 2

    - label: Mal 10
      plugins:
        - docker#v5.12.0:
            image: "huggingface/transformers-torch-light"
            always-pull: true
      commands:
        - "pwd"
        - "ls -la /workdir"
##        - "python3 -m pytest -v tests/models/vit/test_modeling_vit.py::ViTModelTest::test_config"
        - "python3 -m pytest -v tests/models/vit/test_modeling_vit.py -k ViTModelTest"
      parallelism: 2
