  - steps:
    - label: Bon 9
      commands:
        - "echo 9"
        - "echo $(python3 --version)"
      parallelism: 2

    - label: Mal 10
      commands:
        - "echo 10"
        - "echo $(python3 --version)"
      parallelism: 3
