  steps:
    - label: "run_tests in parallel (dynamic)"
      plugins:
        - docker#v5.12.0:
            image: "huggingface/transformers-torch-light"
            always-pull: true
            mount-buildkite-agent: true
            environment:
              - "OMP_NUM_THREADS=1"
              - "BUILDKITE_PARALLEL_JOB"
              - "BUILDKITE_BRANCH"
      # Need to be created dynamically
      parallelism: 2
      commands:
        - "mkdir test_preparation"
        - 'buildkite-agent artifact download "test_preparation/*" test_preparation/ --step fetch_tests'
        - 'echo "show splitted shuffled_tests_torch_test_list.txt"'
        - "tail -10000 test_preparation/splitted_shuffled_tests_torch_test_list.json"
        - 'echo "pip install packages"'
        - "python -m pip install -U -e ."
        - "echo $BUILDKITE_PARALLEL_JOB"
        - "echo $$BUILDKITE_PARALLEL_JOB"
        - 'python -c ''import os; import json; fp = open("test_preparation/splitted_shuffled_tests_torch_test_list.json"); data = json.load(fp); fp.close(); print(data[os.environ["BUILDKITE_PARALLEL_JOB"]]);'''
        - 'TEST_SPLITS=$(python -c ''import os; import json; fp = open("test_preparation/splitted_shuffled_tests_torch_test_list.json"); data = json.load(fp); fp.close(); print(data[os.environ["BUILDKITE_PARALLEL_JOB"]]);'')'
        - "echo $TEST_SPLITS"
        - "echo $$TEST_SPLITS"
        - 'TEST_SPLITS_2=$(python -c ''import os; import json; fp = open("test_preparation/splitted_shuffled_tests_torch_test_list.json"); data = json.load(fp); fp.close(); test_splits = data[os.environ["BUILDKITE_PARALLEL_JOB"]]; test_splits = " ".join(test_splits); print(test_splits);'')'
        - "echo $$TEST_SPLITS_2"
        - "echo $BUILDKITE_BRANCH"
        - "echo $$BUILDKITE_BRANCH"
        - 'echo "run tests with -n 8"'
        - "python -m pytest -n 8 -v $$TEST_SPLITS_2"