steps:
- group: "setup_and_quality"
  key: "setup_and_quality"
  steps:
    # Should NOT include, but we need to make sure `main` is updated
    - label: "update main"
      plugins:
        - docker#v5.12.0:
            image: "huggingface/transformers-quality"
            always-pull: true
      commands:
        - "git fetch origin"
        - "git branch -D main"
        - "git checkout main"
        - "git pull origin main"
        - "git branch --show-current"
        - "echo $(git log -n 1)"
        - "git pull origin main"
        - "git branch --show-current"
        - "echo $(git log -n 1)"
      key: update_main
    - label: "fetch_tests"
      plugins:
        - docker#v5.12.0:
            image: "huggingface/transformers-quality"
            always-pull: true
      commands:
        - "echo $(python3 --version)"
#        - "echo $(git branch | sed -n '/\* /s///p')"
        - "echo $(git log -n 1)"
        - 'echo "pip install packages"'
        # - "uv pip install -U -e ."
#        - "python -m pip install -U -e ."
        - "python -m pip install -e ."
        - "mkdir -p test_preparation"
#        - 'echo "utils/tests_fetcher.py" without tee'
#        - "python utils/tests_fetcher.py"
        - 'echo "utils/tests_fetcher.py" with tee'
        - "python utils/tests_fetcher.py | tee tests_fetched_summary.txt"
##        - "python utils/tests_fetcher.py --filter_tests"
        - "ls -la test_preparation"
        - "ls -la test_preparation/tests_torch_test_list.txt"
        - 'echo "show tests_torch_test_list.txt"'
        - "tail -10000 test_preparation/tests_torch_test_list.txt"
        - 'echo "show tests_generate_test_list.txt"'
        - "tail -10000 test_preparation/tests_generate_test_list.txt"
        - 'echo "show pipelines_torch_test_list.txt"'
        - "tail -10000 test_preparation/pipelines_torch_test_list.txt"
        - 'echo "shuffle tests_torch_test_list.txt"'
        - "shuf test_preparation/tests_torch_test_list.txt > test_preparation/shuffled_tests_torch_test_list.txt"
        - 'echo "split shuffled_tests_torch_test_list.txt"'
        - "python .buildkite/split_tests.py --input_file test_preparation/shuffled_tests_torch_test_list.txt --output_file test_preparation/splitted_shuffled_tests_torch_test_list.json --n_splits 2"
        - "buildkite-agent pipeline upload config2.yml"
      # Need to generate a new file for new jobs/steps then upload
      artifact_paths:
        - "test_preparation/*"
      key: fetch_tests
#    - label: "run_tests_dummy"
#      commands:
#        - "mkdir test_preparation_local"
#        - 'buildkite-agent artifact download "test_preparation/*" test_preparation_local/ --step fetch_tests'
#    - label: "run_tests"
#      plugins:
##        - artifacts#v1.9.0:
##            download: "test_preparation/*"
#        - docker#v5.12.0:
#            image: "huggingface/transformers-torch-light"
#            always-pull: true
#            mount-buildkite-agent: true
#            environment:
#              - "OMP_NUM_THREADS=1"
#      commands:
#        - "ls -la"
#        - "echo $(python3 --version)"
#        - "mkdir test_preparation"
#        - 'buildkite-agent artifact download "test_preparation/*" test_preparation/ --step fetch_tests'
#        - 'echo "show tests_torch_test_list.txt"'
#        - "ls -la test_preparation"
#        - 'echo "show original tests_torch_test_list.txt"'
#        - "tail -10000 test_preparation/tests_torch_test_list.txt"
#        - 'echo "show shuffled tests_torch_test_list.txt"'
#        - "tail -10000 test_preparation/shuffled_tests_torch_test_list.txt"
#        - 'echo "show splitted shuffled_tests_torch_test_list.txt"'
#        - "tail -10000 test_preparation/splitted_shuffled_tests_torch_test_list.json"
#        - 'echo "pip install packages"'
#        - "python -m pip install -U -e ."
#        - 'echo "run tests"'
#        - "python -m pytest -v $(cat test_preparation/shuffled_tests_torch_test_list.txt)"
#        - 'echo "run tests with -n 8"'
#        - "python -m pytest -n 8 -v $(cat test_preparation/shuffled_tests_torch_test_list.txt)"
#      key: run_tests
    # TO be generated dynamically
    - label: "run_tests in parallel"
      plugins:
        - docker#v5.12.0:
            image: "huggingface/transformers-torch-light"
            always-pull: true
            mount-buildkite-agent: true
            environment:
              - "OMP_NUM_THREADS=1"
              - "BUILDKITE_PARALLEL_JOB"
              - "BUILDKITE_BRANCH"
      # Need to be created dynamically
      parallelism: 2
      commands:
        - "mkdir test_preparation"
        - 'buildkite-agent artifact download "test_preparation/*" test_preparation/ --step fetch_tests'
        - 'echo "show splitted shuffled_tests_torch_test_list.txt"'
        - "tail -10000 test_preparation/splitted_shuffled_tests_torch_test_list.json"
        - 'echo "pip install packages"'
        - "python -m pip install -U -e ."
        - "echo $BUILDKITE_PARALLEL_JOB"
        - "echo $$BUILDKITE_PARALLEL_JOB"
        - 'python -c ''import os; import json; fp = open("test_preparation/splitted_shuffled_tests_torch_test_list.json"); data = json.load(fp); fp.close(); print(data[os.environ["BUILDKITE_PARALLEL_JOB"]]);'''
        - 'TEST_SPLITS=$(python -c ''import os; import json; fp = open("test_preparation/splitted_shuffled_tests_torch_test_list.json"); data = json.load(fp); fp.close(); print(data[os.environ["BUILDKITE_PARALLEL_JOB"]]);'')'
        - "echo $TEST_SPLITS"
        - "echo $$TEST_SPLITS"
        - 'TEST_SPLITS_2=$(python -c ''import os; import json; fp = open("test_preparation/splitted_shuffled_tests_torch_test_list.json"); data = json.load(fp); fp.close(); test_splits = data[os.environ["BUILDKITE_PARALLEL_JOB"]]; test_splits = " ".join(test_splits); print(test_splits);'')'
        - "echo $$TEST_SPLITS_2"
        - "echo $BUILDKITE_BRANCH"
        - "echo $$BUILDKITE_BRANCH"
        - 'echo "run tests with -n 8"'
        - "python -m pytest -n 8 -v $$TEST_SPLITS_2"
#        # For the record only
#        - 'if [ "1" = "1" ]; then echo "1"; fi'
#        - 'if [ "1" = "0" ]; then echo "1"; else echo "0"; fi'
#        - |
#          if [ "1" = "1" ]; then
#            echo 1
#          fi
#        - |
#          if [ "1" = "0" ]; then
#            echo 1
#          else
#            echo 0
#          fi
      key: run_tests_in_parallel



#    - label: "Build 1"
#  #    plugins:
#  #      - docker#v5.12.0:
#  #          image: "python:3.10-slim"
#  #          always-pull: true
#      commands:
#        - "echo 3"
#        - "echo 2"
#        - "mkdir logs"
#        - "echo 1 > logs/log.txt"
#        - "ls -l"
#        - "ls -l logs"
#        - "ls -l logs/log.txt"
##        - "sleep 5"
#      artifact_paths:
#        - "logs/log.txt"
#  #      - "conda init"
#  #      - "conda activate py39"
#  #      - "echo 4"
#  #      - "conda deactivate"
#  #      - "echo 6"
#  #      - "echo 7"
#      key: build-1
##    - label: "Build 2"
##  #    plugins:
##  #      - docker#v5.12.0:
##  #          image: "python:3.10-slim"
##  #          always-pull: true
##      commands:
##        - "echo 1"
##        - "echo 2"
##        - "echo 3"
##        - "sleep 5"
##  #      - "conda init"
##  #      - "conda activate py39"
##  #      - "echo 4"
##  #      - "conda deactivate"
##  #      - "echo 6"
##  #      - "echo 7"
##      key: build-2
##    - label: "Build 3"
##  #    plugins:
##  #      - docker#v5.12.0:
##  #          image: "python:3.10-slim"
##  #          always-pull: true
##      commands:
##        - "echo 1"
##        - "echo 2"
##        - "echo 3"
##        - "sleep 5"
##  #      - "conda init"
##  #      - "conda activate py39"
##  #      - "echo 4"
##  #      - "conda deactivate"
##  #      - "echo 6"
##  #      - "echo 7"
##      key: build-3
#- group: ":lock_with_ink_pen: Good boy!"
#  key: "group-2"
#  steps:
#    - label: "Build 1"
#      commands:
#        - "echo 3"
#        - "echo 2"
