steps:
  - label: ":hammer: Build"
    commands:
      - "echo 3"
      - "echo 2"
      - "echo 1"
      - "conda init"
      - "conda activate py39"
      - "echo 4"
      - "conda deactivate"
      - "echo 6"
      - "echo 7"
    key: build