steps:
- group: "setup_and_quality"
  key: "setup_and_quality"
  steps:
    - label: "fetch_tests"
      plugins:
        - docker#v5.12.0:
            image: "huggingface/transformers-quality"
            always-pull: true
      commands:
        - "echo $(python3 --version)"
        - "echo $(git branch)"
        - "echo $(git log -n 1)"
      key: fetch_tests

#    - label: "Build 1"
#  #    plugins:
#  #      - docker#v5.12.0:
#  #          image: "python:3.10-slim"
#  #          always-pull: true
#      commands:
#        - "echo 3"
#        - "echo 2"
#        - "mkdir logs"
#        - "echo 1 > logs/log.txt"
#        - "ls -l"
#        - "ls -l logs"
#        - "ls -l logs/log.txt"
##        - "sleep 5"
#      artifact_paths:
#        - "logs/log.txt"
#  #      - "conda init"
#  #      - "conda activate py39"
#  #      - "echo 4"
#  #      - "conda deactivate"
#  #      - "echo 6"
#  #      - "echo 7"
#      key: build-1
##    - label: "Build 2"
##  #    plugins:
##  #      - docker#v5.12.0:
##  #          image: "python:3.10-slim"
##  #          always-pull: true
##      commands:
##        - "echo 1"
##        - "echo 2"
##        - "echo 3"
##        - "sleep 5"
##  #      - "conda init"
##  #      - "conda activate py39"
##  #      - "echo 4"
##  #      - "conda deactivate"
##  #      - "echo 6"
##  #      - "echo 7"
##      key: build-2
##    - label: "Build 3"
##  #    plugins:
##  #      - docker#v5.12.0:
##  #          image: "python:3.10-slim"
##  #          always-pull: true
##      commands:
##        - "echo 1"
##        - "echo 2"
##        - "echo 3"
##        - "sleep 5"
##  #      - "conda init"
##  #      - "conda activate py39"
##  #      - "echo 4"
##  #      - "conda deactivate"
##  #      - "echo 6"
##  #      - "echo 7"
##      key: build-3
#- group: ":lock_with_ink_pen: Good boy!"
#  key: "group-2"
#  steps:
#    - label: "Build 1"
#      commands:
#        - "echo 3"
#        - "echo 2"
